# Generated by Django 4.2.30 on 2026-05-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Tasvir'), ('slide', 'Slayd'), ('test', 'Test'), ('chat', 'Suhbat')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('content', models.TextField()),
                ('author_id', models.CharField(max_length=128)),
                ('author_name', models.CharField(max_length=255)),
                ('author_photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
