# Generated by Django 4.2.30 on 2026-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('max', 'Max')], max_length=10)),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('card', 'Karta orqali (o‘tkazma)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_details', models.TextField(blank=True, help_text='Tranzaksiya ID yoki chek tafsilotlari')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
